site_name: Vault18 Card Catalog
site_url: https://vault18.github.io
theme:
  name: material
  palette:
    primary: purple
    accent: lime
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Magic:
    - Overview: mtg/index.md
    - The Hobbit: mtg/hobbit.md
  - Pokémon: pokemon/index.md
  - Yu-Gi-Oh: yugioh/index.md
  - Lorcana: lorcana/index.md
  - One Piece: onepiece/index.md
  - Bulk: bulk/index.md

markdown_extensions:
  - tables
  - admonition
  - toc
  - attr_list

plugins:
  - search
